services:
  frontend_api:
    build: ./frontend_api
    ports:
      - "5000:5000"
    volumes:
      - ./frontend_api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  backend_api:
    build: ./backend_api
    ports:
      - "5001:5000"
    volumes:
      - ./backend_api:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - frontend_api
